/*
 * (c) Copyright 2018 Palantir Technologies Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import net.ltgt.gradle.errorprone.CheckSeverity

buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'com.palantir.jakartapackagealignment:jakarta-package-alignment:0.6.0'
        classpath 'com.palantir.gradle.jdks:gradle-jdks:0.82.0'
        classpath 'com.palantir.gradle.jdkslatest:gradle-jdks-latest:0.32.0'
        classpath 'com.palantir.gradle.plugintesting:gradle-plugin-testing:0.6.0'
        classpath 'com.gradle.publish:plugin-publish-plugin:2.1.1'
        classpath 'com.palantir.baseline:gradle-baseline-java:7.0.0'
        classpath 'com.palantir.gradle.consistentversions:gradle-consistent-versions:3.18.0'
        classpath 'com.palantir.gradle.externalpublish:gradle-external-publish-plugin:1.37.0'
        classpath 'com.palantir.gradle.failure-reports:gradle-failure-reports:1.21.0'
        classpath 'com.palantir.gradle.gitversion:gradle-git-version:5.1.0'
        classpath 'com.palantir.gradle.idea-configuration:gradle-idea-configuration:0.11.0'
        classpath 'com.palantir.gradle.idea-language-injector:gradle-idea-language-injector:0.5.0'
        classpath 'com.palantir.javaformat:gradle-palantir-java-format:2.86.0'
        classpath 'com.palantir.suppressible-error-prone:gradle-suppressible-error-prone:2.2.0'
    }
}
allprojects {
    apply plugin: 'com.palantir.jakarta-package-alignment'
}

apply plugin: 'java-gradle-plugin'
apply plugin: 'groovy'
apply plugin: 'idea'

apply plugin: 'com.palantir.baseline'
apply plugin: 'com.palantir.baseline-java-versions'
apply plugin: 'com.palantir.consistent-versions'
apply plugin: 'com.palantir.external-publish-gradle-plugin'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'com.palantir.failure-reports'
apply plugin: 'com.palantir.git-version'
apply plugin: 'com.palantir.gradle-plugin-testing'
apply plugin: 'com.palantir.idea-language-injector'
apply plugin: 'com.palantir.java-format'
apply plugin: 'com.palantir.jdks'
apply plugin: 'com.palantir.jdks.latest'

group 'com.palantir.graal'
version gitVersion()

repositories {
    mavenCentral() { metadataSources { mavenPom(); ignoreGradleMetadataRedirection() } }
}

dependencies {
    implementation localGroovy()
    implementation gradleApi()
    implementation 'com.palantir.gradle.better-exec:better-exec'

    testImplementation gradleTestKit()
    testImplementation 'com.netflix.nebula:nebula-test'
    testImplementation 'com.squareup.okhttp3:mockwebserver'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.spockframework:spock-core'
    testCompileOnly 'junit:junit'
    testRuntimeOnly 'org.spockframework:spock-junit4'
}

gradlePlugin {
    website = 'https://github.com/palantir/gradle-graal'
    vcsUrl = 'https://github.com/palantir/gradle-graal'
    plugins {
        graal {
            id = 'com.palantir.graal'
            displayName = 'Palantir Graal Plugin'
            description = 'A plugin for Gradle that adds tasks to download, extract and interact with GraalVM tooling.'
            implementationClass = 'com.palantir.gradle.graal.GradleGraalPlugin'
            tags = ['graal', 'native-image']
        }
    }
}

tasks.withType(JavaCompile) {
    options.compilerArgs += ['-Werror']
    options.errorprone {
        check("PreferSafeLogger", CheckSeverity.OFF)
        check("PreferSafeLoggingPreconditions", CheckSeverity.OFF)
        check("PreferSafeLoggableExceptions", CheckSeverity.OFF)
        check("Slf4jLogsafeArgs", CheckSeverity.OFF)
    }
}

javaVersions {
    libraryTarget = 17
}

jdks {
    daemonTarget = 21
}
